# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsify', '0002_auto_20160208_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 2, 9, 13, 1, 15, 966600, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
